# Assignment Chapter 2 - MACHINE LEARNING [Case #1]
Startup Campus, Indonesia - `Artificial Intelligence (AI)` (Batch 7)
* Dataset: SC_HW1_bank_data
* Libraries: Pandas, Numpy, Scikit-learn
* Objective: Classification with Supervised Machine Learning Models

`PERSYARATAN` Semua modul (termasuk versi yang sesuai) sudah di-install dengan benar.
<br>`CARA PENGERJAAN` Lengkapi baris kode yang ditandai dengan **#TODO**.
<br>`TARGET PORTFOLIO` Peserta mampu membandingkan akurasi klasifikasi dari berbagai model *supervised learning*.

### Import Library

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterGrid

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from sklearn.linear_model import LogisticRegression
# from imblearn.over_sampling import SMOTE
# from imblearn.under_sampling import RandomUnderSampler

### Read Dataset

In [ ]:
np.random.seed(123)

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Geography        10000 non-null  object 
 3   Gender           10000 non-null  object 
 4   Age              10000 non-null  int64  
 5   Tenure           10000 non-null  int64  
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64  
 8   HasCrCard        10000 non-null  int64  
 9   IsActiveMember   10000 non-null  int64  
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64  
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB


In [ ]:
df.head()

RowNumber  CustomerId Geography  Gender  Age  Tenure    Balance  \
0          1    15634602    France  Female   42       2       0.00   
1          2    15647311     Spain  Female   41       1   83807.86   
2          3    15619304    France  Female   42       8  159660.80   
3          4    15701354    France  Female   39       1       0.00   
4          5    15737888     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [ ]:
df.groupby('Exited').size()

Exited
0    7963
1    2037
dtype: int64

In [ ]:
# TODO: Hilangkan kolom yang tidak relevan untuk pemodelan

df = df.drop(['RowNumber', 'CustomerId'], axis=1).copy()
df.head()

Geography  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0    France  Female   42       2       0.00              1          1   
1     Spain  Female   41       1   83807.86              1          0   
2    France  Female   42       8  159660.80              3          1   
3    France  Female   39       1       0.00              2          0   
4     Spain  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

### Preprocessing

In [ ]:
# TODO: Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True, dtype=int)
df.head()

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42       2       0.00              1          1               1   
1   41       1   83807.86              1          0               1   
2   42       8  159660.80              3          1               0   
3   39       1       0.00              2          0               0   
4   43       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Geography_Germany  Geography_Spain  Gender_Male  
0        101348.88       1                  0                0            0  
1        112542.58       0                  0                1            0  
2        113931.57       1                  0                0            0  
3         93826.63       0                  0                0            0  
4         79084.10       0                  0                1            0

In [ ]:
# TODO: Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
X = df.drop(['Exited'], axis=1)
y = df['Exited']
X.head()

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42       2       0.00              1          1               1   
1   41       1   83807.86              1          0               1   
2   42       8  159660.80              3          1               0   
3   39       1       0.00              2          0               0   
4   43       2  125510.82              1          1               1   

   EstimatedSalary  Geography_Germany  Geography_Spain  Gender_Male  
0        101348.88                  0                0            0  
1        112542.58                  0                1            0  
2        113931.57                  0                0            0  
3         93826.63                  0                0            0  
4         79084.10                  0                1            0

In [ ]:
# scaler = ... # TODO: Lakukan scaling atau normalisasi
# X_transform = scaler.fit_transform(X)

# Normalisasi dilakukan setelah split data train dan test

In [ ]:
# Bagian ini digunakan jika Anda melakukan scaling atau normalisasi.
# Jika tidak, code ini bisa dilewati dan diganti dengan code yang ada di dalam comment.

# X_transform= pd.DataFrame(X_transform, columns = X.columns)
# X_transform = X.copy()

### Train-Test Split

In [ ]:
X_train ,X_test, y_train, y_test = tts(X, y, test_size = 0.25, random_state = 123)
X_train.head()

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9174   61       1       0.00              2          1               1   
4379   29       7       0.00              2          1               1   
541    26       9       0.00              2          1               1   
7251   31       9  138166.30              1          1               0   
1135   31       6  157791.07              2          0               0   

      EstimatedSalary  Geography_Germany  Geography_Spain  Gender_Male  
9174        191370.97                  0                0            1  
4379        138145.62                  0                0            1  
541         153237.59                  0                0            1  
7251         12920.43                  1                0            1  
1135        177994.81                  1                0            1

In [ ]:
# standarisasi data training dan data testing
scaler = StandardScaler()
# scaler.fit(X_train)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Model #1

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #1 yang Anda gunakan.

[ ANSWER HERE ]
<br>Logistic Regression adalah salah satu algoritma machine laearning yang cukup populer untuk kasus klasifikasi biner. Untuk mencari hyperparameter terbaik, digunakan gridsearchcv dengan beberapa hyparameter yang dirasa cocok untuk kasus dan kondisi yang ada.

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(100,), random_state=123, max_iter=500)
mlp.fit(X_train, y_train)

# params = None

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
# grid = GridSearchCV(
#     estimator= model1,
#     param_grid= params,
#     scoring = 'accuracy',
#     n_jobs = 10, # core cpu yang digunakan
#     cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
# )

# grid.fit(X_train,y_train)
# grid.best_params_

MLPClassifier(max_iter=500, random_state=123)

In [ ]:
# TODO: Lakukan evaluasi untuk model #1
y_pred = mlp.predict(X_test)

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.75      0.50      0.60       517

    accuracy                           0.86      2500
   macro avg       0.81      0.73      0.76      2500
weighted avg       0.85      0.86      0.85      2500


[[1898   85]
 [ 261  256]]

0.8616


In [ ]:
# model KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
params ={
    'n_neighbors': [1, 3, 5, 7, 10],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
}

grid = GridSearchCV(
    estimator =knn,
    param_grid =params,
    scoring = 'accuracy',
    n_jobs = 10, # core cpu yang digunakan
    cv = 10
)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)


print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1983
           1       0.72      0.38      0.50       517

    accuracy                           0.84      2500
   macro avg       0.79      0.67      0.70      2500
weighted avg       0.83      0.84      0.82      2500


[[1907   76]
 [ 318  199]]

0.8424


### Model #2

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #2 yang Anda gunakan.

[ ANSWER HERE ]
<br>SVC bekerja dengan cara mencari hyperplane antar kelas. Algoritma SVC ini sangat cocok untuk data yang memiliki dimensi tinggi (memiliki banyak fitur) seperti pada kasus yang pada soal ini yang memiliki 10 fitur. SVC akan mengubah seluruh data menjadi vektor baru kemudian dilanjutkan dengan mencari batas antar kelas yang disebut hyperplane. Untuk mencari hyperplane anatar kelas dilakukan dengan menggunakan kernel trick (memilih kernel yang sesuai) agar klasifikasi memiliki tingkat akurasi dan presisi yang baik. Pada kasus ini, kernel yang digunakan adalah kernel default (Radial Basis Function) karena kernel tersebut menghasilkan model dengan performa yang lebih baik dibanding kernel lain

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn.svm import SVC
model2 = SVC(random_state=123)
model2.fit(X_train, y_train)


# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
# grid = GridSearchCV(
#     estimator = model2,
#     param_grid = params,
#     scoring = 'accuracy',
#     n_jobs = 10, # core cpu yang digunakan
#     cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
# )

# grid.fit(X_train, y_train)
# grid.best_params_

SVC(random_state=123)

In [ ]:
y_pred = model2.predict(X_test) # TODO: Lakukan evaluasi untuk model #2

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1983
           1       0.83      0.41      0.55       517

    accuracy                           0.86      2500
   macro avg       0.85      0.70      0.74      2500
weighted avg       0.86      0.86      0.84      2500


[[1939   44]
 [ 303  214]]

0.8612


### Model #3

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #3 yang Anda gunakan.

[ ANSWER HERE ]
<br>Random Forest adalah salah satu model machine learning yang memiliki resiko overfitting yang lebih rendah. Pada model yang dibuat, digunakan hyperparameter gini sebagai criterion dan untuk menentukan fitur yang digunakan pada tiap pohon menggunakan akar n. Pada model ini juga dilakukan tuning pada hyperparameter class_weight karena terjadi imbalanced data. Dengan mengatur class_weight, random forest dapat menyesuaikan dengan data yang tidak seimbang.

In [ ]:
# CONTOH pemanggilan library dan penggunaannya:

# from sklearn.linear_model import LogisticRegression
# model1 = LogisticRegression()
# params = {"tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(
    criterion='gini',
    class_weight='balanced',
    max_features='sqrt',
    random_state=123,
    n_estimators=200
)
model3.fit(X_train, y_train)


# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
# grid = GridSearchCV(
#     estimator= model3,
#     param_grid= params,
#     scoring = 'accuracy',
#     n_jobs = 10, # core cpu yang digunakan
#     cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
# )

# grid.fit(X_train,y_train)
# grid.best_params_

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=123)

In [ ]:
y_pred = model3.predict(X_test) # TODO: Lakukan evaluasi untuk model #3

print(classification_report(y_test,y_pred))
print("")
print(confusion_matrix(y_test,y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.78      0.48      0.59       517

    accuracy                           0.86      2500
   macro avg       0.83      0.72      0.76      2500
weighted avg       0.86      0.86      0.85      2500


[[1913   70]
 [ 270  247]]

0.864


### Conclusion

In [ ]:
# [ PERTANYAAN ]
# TODO: Tarik kesimpulan model mana yang terbaik beserta alasannya

[ ANSWER HERE ]

### Scoring
Total `#TODO` = 13
<br>Checklist:

- [ ] Hilangkan kolom yang tidak relevan untuk pemodelan
- [ ] Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
- [ ] Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
- [ ] Lakukan scaling atau normalisasi
- [ ] Jelaskan secara singkat model #1 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #1)
- [ ] Lakukan evaluasi untuk model #1
- [ ] Jelaskan secara singkat model #2 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #2)
- [ ] Lakukan evaluasi untuk model #2
- [ ] Jelaskan secara singkat model #3 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #3)
- [ ] Lakukan evaluasi untuk model #3

### Additional readings
- N/A

### Copyright © 2024 Startup Campus, Indonesia
* You may **NOT** use this file except there is written permission from PT. Kampus Merdeka Belajar (Startup Campus).
* Please address your questions to mentors.